# Generated by Django 5.1.7 on 2026-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstructionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error_text', models.TextField(blank=True)),
                ('input_mode', models.CharField(choices=[('images', 'Images'), ('zip', 'ZIP'), ('video', 'Video')], max_length=12)),
                ('algorithm', models.CharField(choices=[('SIFT', 'SIFT'), ('ORB', 'ORB'), ('AKAZE', 'AKAZE')], default='SIFT', max_length=12)),
                ('frame_count', models.PositiveIntegerField(default=20)),
                ('crop_x', models.IntegerField(blank=True, null=True)),
                ('crop_y', models.IntegerField(blank=True, null=True)),
                ('crop_w', models.IntegerField(blank=True, null=True)),
                ('crop_h', models.IntegerField(blank=True, null=True)),
                ('preview_image', models.CharField(blank=True, max_length=400)),
                ('working_dir', models.CharField(blank=True, max_length=400)),
                ('panorama_png', models.CharField(blank=True, max_length=400)),
                ('panorama_jpg', models.CharField(blank=True, max_length=400)),
                ('cameras_json', models.JSONField(blank=True, default=list)),
                ('rectangles_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
